// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class SimpleJsonFormat : Tracker.ITraceFormatter
{

	public string Serialize (List<string> traces)
	{
		String result = "[";	
		foreach (String trace in traces){
			string[] parts = trace.Split(',');
			result += "{\"event\":\"" + parts[0] + "\", " +
				"\"target\":\"" + parts[1] + "\"" +
				( parts.Length == 3 ? ",\"value\":\"" + parts[2] + "\"" : "")
				+ "},";
		}
		return result.Substring(0, result.Length - 1) + "]";
	}
}


