// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using SimpleJSON;

public class SimpleJsonFormat : Tracker.ITraceFormatter
{

	public string Serialize (List<string> traces)
	{
		String result = "[";	
		foreach (String trace in traces){
			string[] parts = trace.Split(',');
			result += "{\"event\":\"" + parts[1] + "\", " +
				"\"target\":\"" + parts[2] + "\"" +
				( parts.Length == 4 ? ",\"value\":\"" + parts[3] + "\"" : "")
				+ "},";
		}
		return result.Substring(0, result.Length - 1) + "]";
	}

    public void StartData(JSONNode data)
    {

    }
}


